
#pragma once

#include"NativeGameplayTags.h"

namespace BlasterGameplayTags
{
	/*Input Tags*/
	BLASTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Move);
	BLASTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Look);
	BLASTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Jump);
	BLASTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Equip);
	BLASTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Crouch);
	BLASTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Aim);
	BLASTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Fire);

	BLASTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Toggleable);

	BLASTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Test);
	BLASTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_MustBeHeld);


	/** Player Tags */
	BLASTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Test);
}